allprojects {
    apply plugin: 'java'
    apply plugin: 'idea'

    idea {
        module {
            downloadJavadoc = true
            downloadSources = true
        }
    }

    repositories {
        mavenCentral()
        maven { url = uri('https://central.sonatype.com/repository/maven-snapshots') }
        maven { url = uri('https://libraries.minecraft.net') }
        maven { url = uri('https://repo.codemc.io/repository/nms/') }
        maven { url = uri('https://jitpack.io') }
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    apply from: "$rootDir/gradle/publish-config.gradle"

    dependencies {
        compileOnlyApi 'net.kyori:adventure-api:4.26.1'
        compileOnlyApi 'net.kyori:adventure-text-minimessage:4.26.1'
        compileOnlyApi 'net.kyori:adventure-text-serializer-legacy:4.26.1'
        api 'com.saicone:types:1.4.3'

        compileOnly 'org.jetbrains:annotations:26.1.0'

        compileOnly fileTree(dir: 'libs', includes: ['*.jar'])
    }

    compileJava {
        options.encoding = 'UTF-8'
    }

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(21))
        withSourcesJar()
        withJavadocJar()
    }

    javadoc {
        options {
            links 'https://docs.oracle.com/en/java/javase/21/docs/api/'
            // adventure
            links 'https://jd.advntr.dev/api/4.26.1/'
            links 'https://jd.advntr.dev/text-minimessage/4.26.1/'
            // annotations
            links 'https://javadoc.io/doc/org.jetbrains/annotations/26.1.0/'
            // types
            links 'https://javadoc.saicone.com/types/'
        }
    }

    publishing {
        publications {
            maven(MavenPublication) {
                from components.java
                artifactId = 'mscript-' + project.name

                pom {
                    afterEvaluate {
                        description = "Module \"${project.name}\" of mscript"
                    }
                }
            }
        }
    }
}

def javadocProjects = [
        ':api',
        ':platform-bukkit',
        ':platform-bungeecord',
        ':platform-velocity',
]

tasks.register('allJavadoc', Javadoc) {
    group = 'documentation'

    source javadocProjects.collect { project(it).sourceSets.main.allJava }
    classpath = files(javadocProjects.collect { project(it).sourceSets.main.compileClasspath }) +
                files(javadocProjects.collect { project(it).configurations.findByName('compileOnlyWith') }.findAll { it != null })
    javadocTool.set(javaToolchains.javadocToolFor {
        languageVersion.set(JavaLanguageVersion.of(25))
    })

    options {
        def allLinks = javadocProjects.collect { projectPath ->
            project(projectPath).javadoc.options.links
        }.flatten().unique()
        allLinks.each { link -> links link }
    }

    destinationDir = file(project.layout.buildDirectory.dir('docs/all-javadoc'))
}
