description = 'MScript API'

repositories {
    maven { url = uri('https://repo.opencollab.dev/main/') }
}

configurations {
    compileOnlyWith
}

dependencies {
    compileOnly 'net.luckperms:api:5.4'
    compileOnly 'org.geysermc.floodgate:api:2.2.5-SNAPSHOT'
    compileOnlyWith 'io.github.miniplaceholders:miniplaceholders-api:3.2.0'

    testImplementation(platform('org.junit:junit-bom:5.14.3'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')

    testImplementation 'net.kyori:adventure-api:4.26.1'
    testImplementation 'net.kyori:adventure-text-minimessage:4.26.1'
    testImplementation 'net.kyori:adventure-text-serializer-legacy:4.26.1'
    testImplementation 'net.kyori:adventure-text-serializer-plain:4.26.1'
    testImplementation 'com.saicone:types:1.4.3'
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

javadoc {
    classpath += configurations.compileOnlyWith
}

tasks.withType(JavaCompile).configureEach {
    classpath += configurations.compileOnlyWith
    options.release = 21
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
    failOnNoDiscoveredTests = false
}

publishing {
    publications {
        maven(MavenPublication) {
            pom {
                afterEvaluate {
                    description = "Script interpreter for Minecraft projects"
                }
            }
        }
    }
}
